[package]
name = "wora"
authors = [ "Adam Flott <adam@adamflott.com>" ]
version = "0.0.1"
edition = "2021"
rust-version = "1.67"
description = "A framework for building applications (daemons, etc) that run in different environments (Linux, Kubernetes, etc)."
readme = "README.md"
repository = "https://github.com/adamflott/wora"
license = "MIT OR Apache-2.0"
categories = ["development-tools"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["full"] }
clap = { version = "4", features = ["derive", "env", "cargo" ] }
signal-hook = { version = "*", features = ["channel", "iterator", "extended-siginfo" ] }
nix = "*"
libc = "*"
chrono = "*"
serde_json = "*"
serde = { version = "*", features = ["derive"] }
log = "*"
fern = "*"
toml = "*"
serde_derive = "*"
statgrab = "*"
tokio-retry = "*"
async-trait = "*"
directories = "*"
notify = "*"
thiserror = "*"
users = "*"
caps = "*"
