[package]
name = "wora"
authors = [ "Adam Flott <adam@adamflott.com>" ]
version = "0.0.1"
edition = "2021"
rust-version = "1.67"
description = "A framework for building applications (daemons, etc) that run in different environments (Linux, Kubernetes, etc)."
readme = "README.md"
repository = "https://github.com/adamflott/wora"
license = "MIT OR Apache-2.0"
categories = ["development-tools"]

[dependencies]
async-trait = "~0.1.67"
chrono = "~0.4.24"
clap = { version = "~4.1.11", features = ["derive", "env", "cargo" ] }
directories = "~5.0.0"
futures = "~0.3.27"
libc = "~0.2.140"
log = "~0.4.17"
nix = "~0.26.2"
notify = "~5.1.0"
opentelemetry = "~0.18.0"
serde_derive = "~1.0.157"
serde_json = "~1.0.94"
serde = { version = "~1.0.157", features = ["derive"] }
statgrab = "~0.9.4"
thiserror = "~1.0.40"
tokio = { version = "~1.26.0", features = ["full"] }
toml = "~0.7.3"
tracing = "~0.1.37"
tracing-subscriber = "~0.3.16"
users = "~0.11.0"

[target.'cfg(target_os = "linux")'.dependencies]
caps = "~0.5.5"
