[package]
name = "wora"
authors = [ "Adam Flott <adam@adamflott.com>" ]
version = "0.0.3"
edition = "2021"
rust-version = "1.67"
description = "A framework for building applications (daemons, etc) that run in different environments (Linux, Kubernetes, etc)."
readme = "README.md"
repository = "https://github.com/adamflott/wora"
license = "MIT OR Apache-2.0"
categories = ["development-tools"]

[dependencies]
async-trait = "~0.1.75"
chrono = { version = "~0.4.31", features = ["serde"] }
clap = { version = "~4.4.11", features = ["derive", "env", "cargo" ] }
decimal-percentage = "~0.1.4"
directories = "~5.0.1"
futures = "~0.3.30"
libc = "~0.2.151"
log = "~0.4.20"
nix = { version = "~0.27.1", features = ["process", "mman", "resource", "fs"]}
notify = "~6.1.1"
opentelemetry = "~0.21.0"
os_info = "~3.7.0"
proc-lock = "~0.4.0"
serde_derive = "~1.0.193"
serde_json = "~1.0.108"
serde = { version = "~1.0.193", features = ["derive"] }
sysinfo = "~0.29.11"
thiserror = "~1.0.52"
tokio = { version = "~1.29.0", features = ["full"] }
toml = "~0.8.8"
tracing = "~0.1.40"
tracing-subscriber = "~0.3.18"
users = "~0.11.0"
vfs = { version = "*", features = ["async-vfs"] }

[build-dependencies]
pkg-config = "0.3.28"

[target.'cfg(target_os = "linux")'.dependencies]
caps = "0.5.5"
